#' Compute Synthetic Control Residuals for Conformal Inference
#'
#' @description
#' Estimates synthetic control weights on the full study period (pre- and
#' post-treatment combined) and returns the residuals of the treated unit
#' relative to its synthetic counterfactual. Outcomes are de-meaned within
#' each unit before estimation. The resulting residuals are passed to
#' \code{\link{get_p_value}} to construct block-permutation conformal
#' p-values.
#'
#' @param data A data frame in long format containing all units and time
#'   periods, including a column for potential outcomes under the null
#'   (typically named \code{"Y0_null"}, generated by
#'   \code{\link{get_Y0_null}}).
#' @param method Character string. Synthetic control method used to estimate
#'   weights. Must be one of \code{"ADH"}, \code{"ADH subset"}, \code{"DID"},
#'   \code{"DIFP"}, \code{"PSC"}, or \code{"1NN matching"}.
#' @param outcome_var Character string. Quoted name of the outcome variable to
#'   use (typically \code{"Y0_null"}).
#' @param treated_var Character string. Quoted name of the binary treatment
#'   indicator column (1 = treated unit, 0 = control).
#' @param time_var Character string. Quoted name of the time identifier column.
#' @param id_var Character string. Quoted name of the unit identifier column.
#' @param post_var Character string. Quoted name of the binary post-treatment
#'   period indicator.
#'
#' @return A tibble with two columns: \code{post} (the post-treatment indicator
#'   vector for the treated unit) and \code{residuals} (de-meaned treated
#'   outcomes minus the synthetic counterfactual). Returns \code{NA} for
#'   \code{residuals} if the optimisation fails.
get_residuals_conformal_inference <- function(data,
                                              method,
                                              outcome_var,
                                              treated_var,
                                              time_var,
                                              id_var,
                                              post_var){
  
  if(!method %in% c("ADH", "ADH subset", "DID", "DIFP", "PSC", "1NN matching")) stop("Please select a valid method - available types are `ADH`, `ADH subset`, `DID`, `DIFP`, `PSC`, `1NN matching`")
  
  # De-mean outcomes by group
  data_demeaned <- data %>% 
    mutate(!!outcome_var := .data[[outcome_var]] - mean(.data[[outcome_var]], na.rm = TRUE), .by = .data[[id_var]])
  
  # Extract vector of treated outcomes and matrices of control outcomes (we use Y_controls_pre and Y_controls_post to tune hyperparameters in the DIFP/PSC methods)
  n_periods <- nrow(distinct(data_demeaned, .data[[time_var]]))
  
  Y_treated <- data_demeaned %>% 
    filter(.data[[treated_var]] == 1) %>%
    pull(.data[[outcome_var]]) %>% 
    as.numeric()
  
  Y_controls <- data_demeaned %>%
    filter(.data[[treated_var]] == 0) %>%
    pull(.data[[outcome_var]]) %>%
    matrix(nrow = n_periods)
  
  # Extract vector of indicators for post-treatment
  post <- data_demeaned %>% 
    filter(.data[[treated_var]]==1) %>%
    pull(.data[[post_var]])
  
  Y_controls_pre <- Y_controls[post == 0,]
  Y_controls_post <- Y_controls[post==1, , drop = FALSE] # Keep as matrix
  
  # Get optimisation results
  
  if(method == "ADH"){
  # ADH
  results_optimisation <- objective_function_adh(Y_treated_pre = Y_treated,
                                                 Y_controls_pre = Y_controls,
                                                 initial_margin = 0.0005,
                                                 max_attempts = 20,
                                                 margin_increment = 0.0005)
  # ADH subset
  } else if(method == "ADH subset"){
    results_optimisation <- objective_function_adh_subset(Y_treated_pre = Y_treated,
                                                   Y_controls_pre = Y_controls,
                                                   n_controls = 20,
                                                   initial_margin = 0.0005,
                                                   max_attempts = 20,
                                                   margin_increment = 0.0005)
    # DID
  } else if(method == "DID"){
    results_optimisation <- objective_function_did(Y_treated_pre = Y_treated,
                                                   Y_controls_pre = Y_controls,
                                                   n_controls = 20)
    # 1NN
  } else if(method == "1NN matching"){
    results_optimisation <- objective_function_1NN_matching(Y_treated_pre = Y_treated,
                                                   Y_controls_pre = Y_controls)
    # DIFP
  } else if(method == "DIFP"){
    
    # Initialise starting values for hyperparameters
    hyper_params <- c("alpha" = 0.5,
                      "lambda" = 2)
    
    # Optimise hyperparameters for elastic net objective function using pseudo-treated units
    results_hyperparams <- optimx(hyper_params,
                                  get_hyperparam_loss_elastic_net,
                                  lower = c(0, 0.1), # Set minimum lambda for stability
                                  upper = c(1, Inf),
                                  Y_controls_pre = Y_controls_pre,
                                  Y_controls_post = Y_controls_post,
                                  method = "L-BFGS-B") # Could maybe try a cv.glmnet or grid search here
    
    # Re-order results to find best solution (assume using minimisation in optimx)
    results_hyperparams <- results_hyperparams[order(results_hyperparams$value,decreasing=FALSE),]
    
    # Retain optimal solution (first row in re-ordered results_opt)
    results_hyperparams <- results_hyperparams[1,]
    
    # Extract optimal hyperparameters (if NA, return initial hyperparams)
    alpha_opt <- ifelse(!is.na(results_hyperparams[["alpha"]]), as.numeric(results_hyperparams[["alpha"]]), alpha_init)
    lambda_opt <- ifelse(!is.na(results_hyperparams[["lambda"]]), as.numeric(results_hyperparams[["lambda"]]), lambda_init)
    
    # Re-run optimisation to get optimal synthetic control weights for treated unit -------------
    # at the optimal level of the hyperparameters
    
    # Run glm model at optimal parameters on the true treated unit during the entire study period (including post-treatment)
    fit <- glmnet(Y_controls, 
                  Y_treated, 
                  alpha = alpha_opt,
                  lambda = lambda_opt,
                  nlambda = 1)
    
    # Extract optimal model coefficients
    W_opt <- fit[["beta"]]
    mu_opt <- fit[["a0"]]
    
    results_optimisation <- list("W_opt" = W_opt,
                                 "mu_opt" = mu_opt)
    
    # PSC
  } else if(method == "PSC"){
    # Initialise starting value for lambda
    par <- c("lambda" = 1)
    lower_bound_lambda <- 1e-6 # same settings as simulation
    
    # Optimise lambda for penalised SC objective function using pseudo-treated units
    results_lambda <- optimx(par,
                             get_hyperparam_loss_penalised_sc,
                             lower = lower_bound_lambda,
                             upper = Inf,
                             Y_controls_pre = Y_controls_pre,
                             Y_controls_post = Y_controls_post,
                             method = "L-BFGS-B") # Could maybe try a cv.glmnet or grid search here
    
    # Re-order results to find best solution (assume using minimisation in optimx)
    results_lambda <- results_lambda[order(results_lambda$value,decreasing=FALSE),]
    
    # Retain optimal solution (first row in re-ordered results_opt)
    results_lambda <- results_lambda[1,]
    
    # Extract optimal hyperparameters (if NA, return initial hyperparams)
    lambda_opt <- ifelse(!is.na(results_lambda[["lambda"]]), as.numeric(results_lambda[["lambda"]]), lambda_init)
    
    # Re-run optimisation to get optimal synthetic control weights for treated unit -------------
    # at the optimal level of the hyperparameters
    
    # Run PSC algorithm at optimal parameters on the true treated unit during the pre-treatment period
    W_opt <- get_penalised_sc_weights(Y_treated,
                                      Y_controls,
                                      lambda_opt)
    
    # Set mu_opt (equal to 0 by design)
    mu_opt <- 0
    
    results_optimisation <- list("W_opt" = W_opt,
                                 "mu_opt" = mu_opt)
  }
  
  W_opt <- results_optimisation$W_opt
  mu_opt <- results_optimisation$mu_opt
  
  # If optimisation succeeded, get predicted Y0 and residuals, if not return NA
  if(!anyNA(W_opt)){
  
  # Compute residuals (de-meaned)
  Y0_pred_demeaned <- as.vector(Y_controls %*% W_opt)
  residuals <- Y_treated - Y0_pred_demeaned
  
  } else {
    residuals <- NA
  }
  
  # Collect results in a dataframe
  results_df <- tibble("post" = post,
                       "residuals" = residuals)
  
  return(results_df)
  
}